### ISSUE TITLE
when will you release the code

### ISSUE THREAD

**Issue by withtimesgo1115** [mmmmimic/diffConvNet#1]
when will you release the code? I want to replay your experiments and verify your idea.

**Comment by withtimesgo1115** [comment]
None of the pigs in the production team can rest as well as you, I guess.

**Comment by mmmmimic** [comment]
Hej Channing, thanks for your interest in our work. We will release the code soon.

**Comment by mmmmimic** [comment]
Hej Channing, now the full codebase has been released

**Comment by withtimesgo1115** [comment]
> Hej Channing, now the full codebase has been released

wow, so quickly !!! Thank you for your amazing work :)
