### ISSUE TITLE
Data can not download

### ISSUE THREAD

**Issue by husnejahan** [mmmmimic/diffConvNet#8]
Hi 
I am trying to download modelnet40_ply_hdf5_2048.zip. But its timeout.

--2023-08-16 13:56:19--  (try: 3)  https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip
Connecting to shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)|171.67.77.19|:443... failed: Connection timed out.
Retrying.

**Comment by mmmmimic** [comment]
Hi! Referring to https://github.com/antao97/PointCloudDatasets, you may want to download the dataset at e.g.  https://cloud.tsinghua.edu.cn/f/b3d9fe3e2a514def8097/. The official link of the dataset could be under maintenance and thus not accessible now.

**Comment by mmmmimic** [comment]
Hi! I just closed the issue. Feel free to reopen it have any further questions.
