### ISSUE TITLE
1

### ISSUE THREAD

**Issue by 950222yjZzz** [mmmmimic/diffConvNet#9]
Hi, thanks for sharing the code. I try to retrain the 3d scene segmentation task on my computer. I get some bugs when I start to train the model. show as below:
`Train 0, loss: 1.834570, train acc: 0.527190, train avg acc: 0.112260, train iou: 0.075878, mean iou: 0.479272

Test 0, loss: 1.757209, test acc: 0.546379, test avg acc: 0.111111, test iou: 0.068297, mean iou: 0.692278

Train 1, loss: 1.718582, train acc: 0.581674, train avg acc: 0.111090, train iou: 0.072744, mean iou: 0.69713

Test 1, loss: 1.735542, test acc: 0.546379, test avg acc: 0.111111, test iou: 0.068297, mean iou: 0.692278`
As you can see, the Test mean iou is not changed, it keeps the value stable (0.692278). Can you give me some suggestions?

**Comment by mmmmimic** [comment]
？hehe
